# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 05:49
from __future__ import unicode_literals
from django.db import migrations, models
import csv


def populate(apps, schema_editor):
    filename = "initial_book_list.txt"
    Book = apps.get_model("mylibrary", "Book")
    with open(filename, "r") as f:
        fields = {"fieldnames": ("title", "author", "copyright", "isbn", "pages", "price", "keyword"), "delimiter": ","}
        reader = csv.DictReader(f, **fields)
        for row in reader:
            b = Book(**row)
            b.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0002_auto_20170412_0544'),
    ]

    operations = [
        migrations.RunPython(populate),
    ]
